[workspace]
resolver = "3"
members = [
    "crates/meloncraft_network",
    "crates/meloncraft_packets",
    "crates/meloncraft_protocol_types",
    "crates/meloncraft_client",
    "crates/meloncraft_handshaking",
    "crates/meloncraft_server_list",
    "crates/meloncraft_player"
]
exclude = [
    "examples"
]

[workspace.dependencies.bevy]
version = "0.17.3"
default-features = false

[package]
name = "meloncraft"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
meloncraft_protocol_types = { path = "crates/meloncraft_protocol_types" }
meloncraft_network = { path = "crates/meloncraft_network" }
meloncraft_client = { path = "crates/meloncraft_client" }
meloncraft_packets = { path = "crates/meloncraft_packets" }
meloncraft_handshaking = { path = "crates/meloncraft_handshaking" }
meloncraft_server_list = { path = "crates/meloncraft_server_list" }
meloncraft_player = { path = "crates/meloncraft_player" }

lazy_static = "1.5.0"

[dependencies]
meloncraft_protocol_types = { workspace = true }
meloncraft_network = { workspace = true }
meloncraft_client = { workspace = true }
meloncraft_packets = { workspace = true }
meloncraft_handshaking = { workspace = true }
meloncraft_server_list = { workspace = true }
meloncraft_player = { workspace = true }
