[package]
name = "meloncraft_login"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
meloncraft_player = { workspace = true }
meloncraft_packets = { workspace = true }
meloncraft_client = { workspace = true }
