[package]
name = "meloncraft_default_registries"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
meloncraft_core = { workspace = true }
meloncraft_nbt = { workspace = true }
meloncraft_protocol_types = { workspace = true }
meloncraft_registry = { workspace = true }
