[package]
name = "meloncraft_protocol_types"
version = "0.1.0"
edition = "2024"

[dependencies]
meloncraft_player = { workspace = true }
meloncraft_core = { workspace = true }
meloncraft_nbt = { workspace = true }
meloncraft_registry = { workspace = true }
meloncraft_text = { workspace = true }
