[package]
name = "meloncraft_incoming_packet_generators"
version = "0.1.0"
edition = "2024"

[dependencies]
meloncraft_packets = { workspace = true }
meloncraft_network = { workspace = true }
bevy = { workspace = true }